/**
 * Returns a copy of the specified string with all Unicode null characters removed.
 */
export function filterNullChars(str: string): string {
  // in HTML generated by Apple Notes I found some null chars (among other things in the tag names)
  return str !== null && str !== undefined
    ? str.replace(new RegExp("\u0000", "g"), "")
    : ""
}
